### ISSUE TITLE
impossible bump com.bugsnag:bugsnag-spring from 3.8.0 to 4.0.0

### ISSUE THREAD

**Issue by dbouclier** [bugsnag/bugsnag-java#261]
### Describe the bug

 After upgrading com.bugsnag:bugsnag-spring from 3.8.0 to 4.0.0, our build fails to compile any class that references the documented com.bugsnag.Bugsnag entry point:

 error: cannot find symbol
 import com.bugsnag.Bugsnag;
                   
 No code change on our side, only the version bump. 

 I'm getting confused by https://github.com/bugsnag/bugsnag-java/blob/v4.0.0/UPGRADING.md still recommends:

```
 @Configuration
 @Import(BugsnagSpringConfiguration.class)
 public class BugsnagConfig {
     @Bean
     public Bugsnag bugsnag() {
         return new Bugsnag("your-api-key-here");
     }
 }
```

 But that code does not compile against bugsnag-spring:4.0.0 alone 

### Expected behavior

 bugsnag-spring should expose the core com.bugsnag:bugsnag artifact on the compile classpath of consumers, as it did in 3.8.0 and as the documented usage requires.

### Environment

 - Gradle 9+, JDK 21+

 Thanks for taking a look.

**Comment by hannah-smartbear** [comment]
Hi @dbouclier,

Thanks for highlighting this. Our engineers will look to re-add com.bugsnag:bugsnag as a dependency of bugsnag-spring. We will let you know once this has been released.

In the meantime, you can import both separately:
```
implementation("com.bugsnag:bugsnag:4.0.0")
implementation("com.bugsnag:bugsnag-spring:4.0.0");
```

**Comment by hannah-smartbear** [comment]
Hi @dbouclier,

Just wanted to let you know that we've now released v4.0.1 of [bugsnag-java](https://github.com/bugsnag/bugsnag-java/releases/tag/v4.0.1) which includes a fix for this.
